name: CI/CD for Booklist Manager

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      MONGO_URI: mongodb://localhost:27017/booklist_db

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📥 Install dependencies
        run: |
          cd backend
          npm install

      - name: ✅ Run tests
        run: |
          cd backend
          chmod +x ./node_modules/.bin/jest || true
          npx jest --coverage

      - name: 📊 Upload coverage report
        uses: actions/upload-artifact@main
        with:
          name: coverage-report
          path: backend/coverage/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

  steps:
    - name: 🚀 Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}   # Check if this is correctly referencing the EC2 Host secret
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}     # Ensure EC2_KEY is correctly set
        script: |
          echo "📂 Navigating to the app directory..."
          cd /home/ec2-user/booklist-manager/backend || { echo "❌ Directory not found"; exit 1; }

          echo "🔄 Pulling latest changes..."
          git pull origin main || { echo "❌ Git pull failed"; exit 1; }

          echo "📦 Installing dependencies..."
          npm install || { echo "❌ npm install failed"; exit 1; }

          echo "♻️ Restarting or starting the app..."
          pm2 restart all || pm2 start server.js --name booklist-api

          echo "📋 Checking logs..."
          tail -n 100 /var/log/syslog 2>/dev/null || tail -n 100 /var/log/messages 2>/dev/null || echo "⚠️ No logs found."

          echo "🩺 Running health check..."
          curl --fail http://localhost:5000/health || { echo "❌ Health check failed"; exit 1; }

          echo "✅ Application deployed and healthy!"


  logging:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🛠️ Install logging utilities
        run: sudo apt-get install -y jq

      - name: 🧾 Generate and analyze logs
        run: |
          echo "📝 Generating logs..."
          echo "$(date) - Deployment successful" >> app.log
          tail -n 10 app.log

      - name: ☁️ Push logs to remote service (optional)
        run: |
          echo "📤 Pushing logs..."
          curl -X POST -H "Content-Type: text/plain" --data-binary @app.log https://log-management-service.com/api/logs || echo "⚠️ Log push failed (optional)"
